apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deployment
  labels:
    app: dev
    env: dev
spec:
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
        env: dev
    spec:
      containers:
      - name: dev
        image: bopgeek/flask-web:v1
        resources:
          limits:
            memory: 1Gi
            cpu: "500m"
          requests:
            memory: 1Gi
            cpu: "500m"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: dev-svc
  labels:
    app: dev
    env: dev
spec:
  selector:
    app: dev
  ports:
  - port: 7000
    targetPort: 5000
    name: http-dev
  type: LoadBalancer

