---
# Source: dev/templates/configmap-xml.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  app.xml: |
---
# Source: dev/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    database:
      ip: 120.21.31.10
      name: ui-qa
    logfile: /app/var/log.txt
    timeout: 5s
---
# Source: dev/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    env: qa
spec:
  type: LoadBalancer
  ports:
  - port: 81
    targetPort: 81
    protocol: TCP
    name: qa
  selector:
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: release-name
---
# Source: dev/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name
  labels:
    helm.sh/chart: dev-0.1.0
    app.kubernetes.io/name: dev
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    env: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: dev
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dev
        app.kubernetes.io/instance: release-name
        env: qa
    spec:
      containers:
      - name: dev
        image: "bopgeek/flask-web:v1"
        pullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 500m
            memory: 128Mi
        ports:
        - containerPort: 5000
          name: qa
