apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
     {{- include "dev.labels" . | nindent 4 }}
data:
  {{ .Values.configxml.name }}: |
  {{ $path := ( printf "config/%v/config.xml"  .Values.env ) }}
  {{ .Files.Get $path | nindent 4 }}