apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "dev.labels" . | nindent 4 }}
    env: {{ .Values.env }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    {{- include "dev.selectorLabels" . | nindent 4 }}
